# site settings
title: Sharif Saleki
subtitle: Cognitive Neuroscience
email: sharif.saleki.gr@dartmouth.edu
description: "Cognitive Neuroscience Ph.D. Student at Dartmouth College"
baseurl: "/" # the subpath of your site, e.g. /blog
url: devxl.github.io # the base hostname & protocol for your site
author: Sharif Saleki
street_address: Moore Hall, Dartmouth College
city: Hanover
state: NH
zip_code:
country: United States of America
phone: (603) 277-8811

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 4

# social settings
500px_url:
facebook_url:
github_url: https://github.com/DevXl/
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url: https://www.linkedin.com/in/andrew-banchich-a4ba1195
pinterest_url:
slack_url:
twitter_url: https://twitter.com/sh4r11f

# build settings
markdown: kramdown

sass:
  style: compressed
